application:
  config:
    db-File: ./data.db
    ffmpeg-bin-file-path: D:\Program Files\m3u8-downloader/bin/ffmpeg.exe

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:${application.config.db-File}